services:
  site:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./astro.config.mjs:/app/astro.config.mjs
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev
